/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab6;

public class Components {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Components().getGreeting());
    }
}
