/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab6;

import org.junit.Test;
import static org.junit.Assert.*;

public class ComponentsTest {
    @Test public void appHasAGreeting() {
        Components classUnderTest = new Components();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
